### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by seanc-dev** [productpeople/website#7]
* [x] Component CardService fix overflow issue
* [x] Component CardService fix image url
* [x] Check width issues on responsive grids
* [x] Drop top box on mobile
* [x] Add anchors
* [x] Update speaker logos
* [x] Cookie banner
* [x] Particle background
* [x] Menu
* [x] Header
* [x] Footer
* [x] Add a `link` prop to the `<ButtonBig` component

**Comment by seanc-dev** [comment]
* [x] Prefer partner logos in size and colour of design
* [x] Component GridUserLogos fix responsive padding/sizing

**Comment by seanc-dev** [comment]
* [x] CaseStudyCard 2 heycar image height is less than in Figma
* [x] CaseStudyCard 3 Körber Digital image does not have logo overlapping in top-left corner

**Comment by mirelamus** [comment]
* [x] set a solid background for the header
* [x] set a favicon, Mirela sends the .ico file  ->  https://en.wikipedia.org/wiki/Favicon#How_to_use
* [x] Investigate if there's something we can configure in particles.js that doesn't eat up too much CPU resources, Emil noticed it affects

**Comment by mirelamus** [comment]
favicon files

**Comment by mirelamus** [comment]
here they are -> [favicons.zip](https://github.com/productpeople/website/files/4209821/favicons.zip)
